### ISSUE TITLE
anew not found

### ISSUE THREAD

**Issue by c-steve-wang** [rix4uni/uforall#1]
root@cb8b1d97bced:/workspace# uforall -d apnews.com -t 100
/root/bin/UForAll/uforall: line 49: anew: command not found
/root/bin/UForAll/uforall: line 50: anew: command not found

**Comment by rix4uni** [comment]
Use this command to install anew:
go install -v github.com/tomnomnom/anew@latest

Now this command working perfectly:
uforall -d apnews.com -t 100
